# Generated by Django 4.2.3 on 2023-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MafiAStarApp', '0002_remove_song_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_image_file',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
