# Generated by Django 4.2.3 on 2023-07-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MafiAStarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='upload_date',
        ),
    ]
