# Generated by Django 4.2.4 on 2023-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MafiAStarApp", "0003_alter_song_song_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="song_image_file",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
