# Generated by Django 4.1.9 on 2023-12-13 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MafiAStarApp', '0004_alter_song_song_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
