name: build
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

jobs:
  build-container:
    uses: fsinfuhh/workflows/.github/workflows/build_image.yml@main
